//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlApar.az.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ad()
        {
            this.Images = new HashSet<Image>();
            this.ElanProfileFavours = new HashSet<ElanProfileFavour>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string OwnerName { get; set; }
        public bool OwnerType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string PinCode { get; set; }
        public int CityId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> VillageId { get; set; }
        public string Text { get; set; }
        public string Phone { get; set; }
        public string XLocation { get; set; }
        public string YLocation { get; set; }
        public Nullable<int> AgentId { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public bool VIP { get; set; }
        public bool Kupca { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> BuildingTypeId { get; set; }
        public string Mertebe { get; set; }
        public string BinaMertebesi { get; set; }
        public string Sahe { get; set; }
        public string TorpaqSahesi { get; set; }
        public string Email { get; set; }
        public string Adress { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual BuildingType BuildingType { get; set; }
        public virtual Category Category { get; set; }
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElanProfileFavour> ElanProfileFavours { get; set; }
        public virtual Profile Profile { get; set; }
        public virtual Region Region { get; set; }
        public virtual RoomCount RoomCount { get; set; }
        public virtual Village Village { get; set; }
    }
}
