//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlApar.az.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class alaparSql2Entities : DbContext
    {
        public alaparSql2Entities()
            : base("name=alaparSql2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Ad> Ads { get; set; }
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<BuildingType> BuildingTypes { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<complain> complains { get; set; }
        public virtual DbSet<ElanProfileFavour> ElanProfileFavours { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<RoomCount> RoomCounts { get; set; }
        public virtual DbSet<Village> Villages { get; set; }
    }
}
